### ISSUE TITLE
[turborepo] CLI is not able to find/detect npm

### ISSUE THREAD

**Issue by OMzaiswal** [vercel/turbo#6084]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

When I am using "npx create-turbo@latest" it is not able to detect npm
But when I replace 'latest' with '1.8.8', it's working
i.e Using "npx create-turbo@1.8.8" instead of "npx create-turbo@latest" works
I am using (ubuntu 22.04), (node v18.18.0),  (npm [10.1.0)

![Screenshot from 2023-10-01 14-42-05](https://github.com/vercel/turbo/assets/72777670/43edb4de-ae43-4578-a94d-1d67b5269225)

![Screenshot from 2023-10-03 14-05-05](https://github.com/vercel/turbo/assets/72777670/1ee7a854-72d9-45ca-a04c-06dbc7ceeeb1)

### Expected Behavior

"npx create-turbo@latest" should produce this behaviour

![Screenshot from 2023-10-03 14-05-29](https://github.com/vercel/turbo/assets/72777670/869d7d95-427d-47af-b964-a9b6a4f00d49)

### To Reproduce

Use "npx create-turbo@latest" command in terminal

![Screenshot from 2023-10-03 14-03-46](https://github.com/vercel/turbo/assets/72777670/c505ae26-5fc7-4e96-ade5-c34c3b45a8f3)

<sub>[TURBO-1400](https://linear.app/vercel/issue/TURBO-1400/[turborepo]-cli-is-not-able-to-finddetect-npm)</sub>

**Comment by chris-olszewski** [comment]
Can you run `which -a npm` and how you installed `npm`?

**Comment by OMzaiswal** [comment]
run  `which -a npm`

![image](https://github.com/vercel/turbo/assets/72777670/cec8050c-6163-416e-a92a-04f98c45ff2d)

**Comment by chris-olszewski** [comment]
Interesting, we determine if a package manager is installed by just calling `npm --version` (and `yarn --version` etc) in the OS temporary directory. Can you see what happens if you run `COREPACK_ENABLE_STRICT=0 npm --version` in whatever directory `cd $TMPDIR` takes you to?

**Comment by OMzaiswal** [comment]
![Screenshot from 2023-10-04 09-20-33](https://github.com/vercel/turbo/assets/72777670/09f2bd68-04ae-411f-a4a1-f1f3069a8909)

**Comment by chris-olszewski** [comment]
I'm at a loss, [that's the exact command we run](https://github.com/vercel/turbo/blob/main/packages/turbo-utils/src/managers.ts#L10-L14) to determine if a package manager is installed. I've tried your specific npm/node version combination and I'm unable to reproduce.

A few things:
 - I could add some debug logging to this codepath to figure what exactly about your setup is causing us to only miss these binaries.
 - Could you try running `npx create-turbo@latest` in `/tmp`?

**Comment by OMzaiswal** [comment]
tried `npx create-turbo@latest` in /tmp

![image](https://github.com/vercel/turbo/assets/72777670/acc6ca3a-62eb-47cd-8096-19a2ce2e00fb)

**Comment by OMzaiswal** [comment]
`npx create-turbo@1.8.8` works properly 
This issue only happens when I run `npx create-turbo@latest` 
I don't know what is causing the problem.

**Comment by nathanhammond** [comment]
@OMzaiswal can you help us bisect to the last working version for you? Here is the list of versions which had changes:

```
1.9.0-canary.1
1.9.2-canary.0
1.9.2-canary.1
1.9.4-canary.11
1.9.5
1.9.9
1.10.2-canary.1
1.10.4-canary.0
1.10.9
1.10.13-canary.0
1.10.13-canary.1
1.10.13
1.10.14-canary.0
1.10.14-canary.1
1.10.14-canary.2
1.10.15-canary.0
```

If you can help us identify when it stopped working for you we can maybe isolate the behavior difference.

**Comment by OMzaiswal** [comment]
I tried all the version that you have mentioned, 1.10.9 is the last working version for me.

![Screenshot from 2023-10-05 12-39-44](https://github.com/vercel/turbo/assets/72777670/c108b211-5c28-4f38-a092-da69715fd7f6)
![Screenshot from 2023-10-05 12-40-46](https://github.com/vercel/turbo/assets/72777670/b1e8181f-d83a-437f-80b9-3922de8f6540)
![Screenshot from 2023-10-05 12-42-15](https://github.com/vercel/turbo/assets/72777670/22b52210-d551-48c3-8c87-e081ea4239b8)
![Screenshot from 2023-10-05 12-43-02](https://github.com/vercel/turbo/assets/72777670/2a7aa135-ec77-46e1-b73f-c6b469a8334b)
![Screenshot from 2023-10-05 12-43-42](https://github.com/vercel/turbo/assets/72777670/6230f2ce-2221-47fc-981d-f07965ad1919)

**Comment by nathanhammond** [comment]
Thank you! The change in question:
https://github.com/vercel/turbo/pull/5279/files#diff-37e68db2edd31eaeecf3e31f1da27f873acb031157f134708b10d5b45e0f3de8

**Comment by OMzaiswal** [comment]
There was an issue with my npm, but it is now resolved. 
`npx create-turbo@latest` is working perfectly. 
Thanks.

**Comment by chris-olszewski** [comment]
Out of curiosity, what was the issue with your npm? Asking in case other users hit the same issue

**Comment by OMzaiswal** [comment]
I am not sure about the issue but something was wrong with the installation and packages. The solution that worked for me was to uninstall Node and npm, followed by a fresh installation. Now it's working perfectly.

**Comment by Abhinavbhar** [comment]
i was also facing the same issue but reinstalling does not fix it but this 1.10.9 version works fine. Thanks
