### ISSUE TITLE
Freeze build on (sorta) circular dependency

### ISSUE THREAD

**Issue by steveruizok** [vercel/turbo#675]
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

I am able to freeze the `turbo run build` pipeline.

- Package A has a dependency on Package B
- Package B has a **dev** dependency on Package A

### Expected Behavior

True circular dependencies should probably cause a crash during build, but not circular dev dependencies. (I don't think devDependencies should matter during build).

### To Reproduce

- Create two packages, A and B
- Add A as a dependency of B
- Add B as a dev dependency of A

Uploaded to: https://codesandbox.io/s/y5ed3

**Comment by steveruizok** [comment]
(Upon reflection, I realize this loop is pretty weird. In practice, A is a client and B is a server. The server has a dependency on the client. However, it's easier to test the server in the client repo, so that's why the dev dependency exists there. Chances are this will all be cleaned up as the project matures, but I figured it's unexpected behavior regardless!)

**Comment by jaredpalmer** [comment]
From turbo's perspective, cycles are cycles and are not allowed. Need to think more about this

**Comment by sibelius** [comment]
this changed somehow from 1.2.3 to 1.2.4

showing this error:

ERROR  Found cycles in package dependency graph

**Comment by NullVoxPopuli** [comment]
@jaredpalmer how about if `package B`'s `devDependencies` has `package A` that has a `devDependencies` entry on `package B`?

This is a cycle, and if the packages needed to _build_, it would not be possible to resolve the cycle.
_however_ both packages do not need to build, and are node tools, so we can afford a little looseness here. If turbo had a way to _ignore_ packages entirely, that would be a sufficient scenario for this use case -- opting out entirely of the turbo pipeline.

the scenario is: 
 - test-helpers (dev) depend on lint package
 - lint package uses (dev) test-helpers package to run tests

**Comment by lodmfjord** [comment]
I think it is valid that the program fails on circular dependencies. 

But maybe it would be better to just report instantly:
Circular dependency.

and fail.

**Comment by kellyselden** [comment]
Since NPM doesn't download a dependency's devDependencies, I don't think you can introduce a cycle that way. Having a linting package that uses a testing package for its tests, and the testing package using the linting package is an acceptable dev dependency loop that we have been using and works in yarn and nx. It only started failing when trying out turbo.

**Comment by stramel** [comment]
I just ran into this issue for a monorepo that I'm building. I setup my configs as packages and am depending on the package itself to run some tests against it. My setup is as follows,

`@myorg/browserslist-config` which defines a sharable `.browserslistrc` file. I then installed that package as a `devDependency` using Yarn v3 `"@myorg/browserslist-config": "workspace:*",` as the key and value. With that, I'm able to reference the package (`extends @myorg/browserslist-config`) directly to ensure the `browserslist` CLI properly reads the config and prints the correct list of browsers. I do this with my eslint, prettier, tsconfig, postcss, stylelint, and commitlint configs. 

Would love to be able to utilize turbo for these "tests"/"checks" that I have implemented.

**Comment by productdevbook** [comment]
`"turbo": "1.3.1",` some problem

**Comment by cameronbrill** [comment]
I'm thinking what if we just have a task configuration option to disable connecting dev dependencies in the dag

**Comment by vinibgoulart** [comment]
Checking just using the package.json `dependencies` is an error, this does not actually check if there is a circular dependency, it just assumes it.

While this is being verified, it would be nice to have a flag that ignores this behavior, so that it is not necessary to return the turbo version to 1.2.3

**Comment by NicholasLYang** [comment]
Hi @steveruizok, is there any chance you could confirm that this issue is still occurring in the latest version of Turbo?

For the record, we do consider dev dependencies to still be dependency relations, so a circular dependency error is expected behavior here.

**Comment by NicholasLYang** [comment]
Closed due to lack of reproduction. If this is still occurring, feel free to open a new issue.
