### ISSUE TITLE
Cached files differ from original command execution's output files

### ISSUE THREAD

**Issue by trappar** [vercel/turbo#7410]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/trappar/turbo-cache-missing-output-files

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.12.4

### Describe the Bug

When building my app with turbo, I have it configured to cache the `.next` directory. I noticed that if I build, then delete the `.next` directory, then recover it from my turbo cache - the resulting files differ from the original files I had after building.

### Expected Behavior

The files cached by turbo cache should precisely match the original output files.

### To Reproduce

The reproduction repo I linked has a `reproduce-issue.sh` script that you can run to see the issue. Since this is a minimal reproduction repo, the number of divergent files between the fresh and cached copies are minimal. In a large enterprise monorepo I work on, the number of files not being copied is massive and is causing our servers to error/crash when we try to run a build which was recalled from the turbo cache.

Just for context, here's all that I'm doing in that script:

```
pnpm turbo build --force
mv .next output/force-build

pnpm turbo build
mv .next output/cache-hit-build

diff --brief --recursive output/force-build output/cache-hit-build
```

And this is producing the following list of file differences:
```
Only in output/cache-hit-build/standalone/node_modules/.pnpm/@swc+helpers@0.5.2/node_modules/@swc/helpers/_: _interop_require_
Only in output/cache-hit-build/standalone/node_modules/.pnpm/caniuse-lite@1.0.30001587/node_modules/caniuse-lite/data: feature
Only in output/cache-hit-build/standalone/node_modules/.pnpm/caniuse-lite@1.0.30001587/node_modules/caniuse-lite/dist: unpacke
Only in output/cache-hit-build/standalone/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/@swc/helpers/_: _interop_require_
Only in output/cache-hit-build/standalone/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/caniuse-lite/data: feature
Only in output/cache-hit-build/standalone/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/caniuse-lite/dist: unpacke
```

> **Note:** strangely in the real project the original build contains files which are then missing from the cache-hit version. Here it's the opposite? This makes no sense to me.

### Additional context

The only context where I've seen this happen is a Next.js app using the "standalone" output mode. I suspect this is because the directory I'm trying to cache has long file paths and complex/internal links. It's possible that this could be distilled down even further into a reproduction that simply creates a directory structure like what Next.js creates, but this is probably the best repo since it's a fairly common application configuration.

I know this issue can be reproduced on Ubuntu and on Mac since I'm seeing these kinds of failures in CI, and I've reproduced it locally in that reproduction repo. I'm curious if this bug will happen on all OSes (windows?)

<sub>[TURBO-2414](https://linear.app/vercel/issue/TURBO-2414/cached-files-differ-from-original-command-executions-output-files)</sub>

**Comment by trappar** [comment]
I've been digging at this trying to replicate the issue without using a next build and have come up with nothing helpful, but in the process I found something very interesting...

Simply manually unarchiving the files from the turbo cache `.tar.zst` file yields an identical match to the original output files. This works in my reproduction repo and my big complicated monorepo project.

The command I'm using to unarchive the files is: `tar --use-compress-program=unzstd -xvf xxx.tar.zst`

So this tells me that the issue is probably one of:
1. Turbo is doing something post-unarchive to the files.
2. This bug is within whatever Turbo is using to unarchive the files.

**Comment by trappar** [comment]
Just went through tested turbo versions to see if there was a point in the past where this issue didn't exist and then where it appeared. Here's a timeline of what I found:
* `1.10.16`: Cache matches original files exactly.
* `1.11.0` - `1.11.2`:  Couldn't test due error "Error with daemon: server is unavailable".
* `1.11.3`: Still getting errors from turbo, but differences between original files / cached files start to appear.
* `1.12.0` - `1.12.4`: No errors from turbo, differences between original files / cached files observed.

I looked through the 1.11.0 changes and this one stuck out to me: https://github.com/vercel/turbo/pull/6662

I tried downgrading my monorepo project to `1.10.16` and everything is working perfectly.

**Comment by arlyon** [comment]
Thanks for the detailed write-up! I am going to work through some of this and see if I can identify a fix.

**Comment by arlyon** [comment]
Hey, had a look at the code directly and diff you identified and tried to write some tests but can't trigger the behaviour. Your repro-repo is private I think (I am getting a 404). Mind flipping it to public?

**Comment by trappar** [comment]
D'oh... yeah that was a mistake. It's public now.

**Comment by trappar** [comment]
Any update? Have you been able to reproduce the issue in the repo?

**Comment by bmelonis** [comment]
Possibly related to https://github.com/vercel/turbo/issues/6823.  See if you can replicate the error message from that issue on Turbo 1.11.

**Comment by chris-olszewski** [comment]
@trappar Again, thanks for the reproduction and detailed write up. It made finding the issue a lot easier.

https://github.com/vercel/turbo/pull/7628 should fix this.

**Comment by trappar** [comment]
How can I install that version in my big monorepo project so I can do a more thorough test?

**Comment by chris-olszewski** [comment]
> can install that PR's version locally

You can checkout that PR and `cargo build -p turbo` and then use that binary with `--skip-infer` to test, but that requires getting a dev environment setup.

I'm cutting a canary you can use in your project by just changing the `turbo` version. Once [this workflow](https://github.com/vercel/turbo/actions/runs/8162788992) finishes you can use `1.12.5-canary.1` which will have that PR in it.

**Comment by trappar** [comment]
Just ran my tests against my monorepo project and I can confirm that this fixed part of the issue - the part that showed up in my repro repo, but this doesn't actually fix the bulk of the problems.

Would you like me to open a new issue?

I'm honestly not sure if I'll be able to make a repro of the issues I'm seeing, but here's the diff which I assembled using a similar script to the one from my repro repo:
```
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules/@emotion: serialize
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules/@emotion: use-insertion-effect-with-fallbacks
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules/@emotion: utils
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules/@emotion: weak-memoize
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules: hoist-non-react-statics
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules/@emotion: use-insertion-effect-with-fallbacks
Only in output/force-build/standalone/node_modules/.pnpm/@emotion+styled@11.11.0_@emotion+react@11.11.1_@types+react@18.2.51_react@18.3.0-canary-627b7abd6-20230911/node_modules/@emotion: utils
Only in output/force-build/standalone/node_modules/.pnpm/@formatjs+icu-messageformat-parser@2.3.0/node_modules/@formatjs: icu-skeleton-parser
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+dialog@3.5.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: focus
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+dialog@3.5.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: overlays
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+dialog@3.5.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: utils
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+focus@3.11.0_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: interactions
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+focus@3.11.0_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: utils
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+focus@3.11.0_react@18.3.0-canary-627b7abd6-20230911/node_modules/@swc: helpers
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+focus@3.11.0_react@18.3.0-canary-627b7abd6-20230911/node_modules: clsx
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+i18n@3.7.0_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: ssr
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+interactions@3.14.0_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: utils
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+overlays@3.13.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: ssr
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+overlays@3.13.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: utils
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+overlays@3.13.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-aria: visually-hidden
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+overlays@3.13.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+utils@3.15.0_react@18.3.0-canary-627b7abd6-20230911/node_modules/@react-stately: utils
Only in output/force-build/standalone/node_modules/.pnpm/@react-aria+utils@3.15.0_react@18.3.0-canary-627b7abd6-20230911/node_modules: clsx
Only in output/force-build/standalone/node_modules/.pnpm/@rollup+plugin-commonjs@24.0.0_rollup@2.78.0/node_modules/@rollup: pluginutils
Only in output/force-build/standalone/node_modules/.pnpm/@rollup+plugin-commonjs@24.0.0_rollup@2.78.0/node_modules: commondir
Only in output/force-build/standalone/node_modules/.pnpm/@rollup+plugin-commonjs@24.0.0_rollup@2.78.0/node_modules: estree-walker
Only in output/force-build/standalone/node_modules/.pnpm/@rollup+plugin-commonjs@24.0.0_rollup@2.78.0/node_modules: glob
Only in output/force-build/standalone/node_modules/.pnpm/@rollup+plugin-commonjs@24.0.0_rollup@2.78.0/node_modules: is-reference
Only in output/force-build/standalone/node_modules/.pnpm/@rollup+pluginutils@5.0.4_rollup@2.78.0/node_modules: estree-walker
Only in output/force-build/standalone/node_modules/.pnpm/@sentry+nextjs@7.86.0_next@14.0.3_react@18.3.0-canary-627b7abd6-20230911_webpack@5.89.0/node_modules/@sentry: node
Only in output/force-build/standalone/node_modules/.pnpm/@sentry+nextjs@7.86.0_next@14.0.3_react@18.3.0-canary-627b7abd6-20230911_webpack@5.89.0/node_modules/@sentry: utils
Only in output/force-build/standalone/node_modules/.pnpm/@sentry+nextjs@7.86.0_next@14.0.3_react@18.3.0-canary-627b7abd6-20230911_webpack@5.89.0/node_modules: chalk
Only in output/force-build/standalone/node_modules/.pnpm/@sentry+nextjs@7.86.0_next@14.0.3_react@18.3.0-canary-627b7abd6-20230911_webpack@5.89.0/node_modules: next
Only in output/force-build/standalone/node_modules/.pnpm/@sentry+nextjs@7.86.0_next@14.0.3_react@18.3.0-canary-627b7abd6-20230911_webpack@5.89.0/node_modules: resolve
Only in output/force-build/standalone/node_modules/.pnpm/@sentry+nextjs@7.86.0_next@14.0.3_react@18.3.0-canary-627b7abd6-20230911_webpack@5.89.0/node_modules: rollup
Only in output/force-build/standalone/node_modules/.pnpm/@webassemblyjs+ast@1.11.6/node_modules/@webassemblyjs: helper-numbers
Only in output/force-build/standalone/node_modules/.pnpm/@webassemblyjs+wasm-edit@1.11.6/node_modules/@webassemblyjs: wasm-gen
Only in output/force-build/standalone/node_modules/.pnpm/@webassemblyjs+wasm-edit@1.11.6/node_modules/@webassemblyjs: wasm-opt
Only in output/force-build/standalone/node_modules/.pnpm/next@14.0.3_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: postcss
Only in output/force-build/standalone/node_modules/.pnpm/next@14.0.3_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react
Only in output/force-build/standalone/node_modules/.pnpm/next@14.0.3_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react-dom
Only in output/force-build/standalone/node_modules/.pnpm/next@14.0.3_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: styled-jsx
diff: output/force-build/standalone/node_modules/.pnpm/node_modules/caniuse-lite: No such file or directory
Only in output/force-build/standalone/node_modules/.pnpm/[redacted]@30.1.4_@emotion+react@11.11.1_@emotion+styled@11.11.0_react-dom@18.3.0-canary-627_vcflnxxyig2c6kyanflnydo4p4/node_modules: react
Only in output/force-build/standalone/node_modules/.pnpm/[redacted]@30.1.4_@emotion+react@11.11.1_@emotion+styled@11.11.0_react-dom@18.3.0-canary-627_vcflnxxyig2c6kyanflnydo4p4/node_modules: react-dom
Only in output/force-build/standalone/node_modules/.pnpm/[redacted]@30.1.4_@emotion+react@11.11.1_@emotion+styled@11.11.0_react-dom@18.3.0-canary-627_vcflnxxyig2c6kyanflnydo4p4/node_modules: react-slick
Only in output/force-build/standalone/node_modules/.pnpm/[redacted]@30.1.4_@emotion+react@11.11.1_@emotion+styled@11.11.0_react-dom@18.3.0-canary-627_vcflnxxyig2c6kyanflnydo4p4/node_modules: react-toggle-button
Only in output/force-build/standalone/node_modules/.pnpm/[redacted]@30.1.4_@emotion+react@11.11.1_@emotion+styled@11.11.0_react-dom@18.3.0-canary-627_vcflnxxyig2c6kyanflnydo4p4/node_modules: react-transition-group
Only in output/force-build/standalone/node_modules/.pnpm/react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react
Only in output/force-build/standalone/node_modules/.pnpm/react-slick@0.29.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react
```

**Comment by chris-olszewski** [comment]
Interesting. Are those diffs a regression compared to the previous canary or are those files missing in the cache hit on both `1.12.5-canary.0` and `1.12.5-canary.1`? I'll reopen this issue to keep discussion in one place.

Are the files missing from the cache hit all just regular files?

**Comment by trappar** [comment]
As far as I can tell those diffs are a subset of the diffs that I originally saw when testing 1.12.4. I'll downgrade to 1.12.5-canary.0 and try rerunning. Will update this comment once I have those results.

**Comment by trappar** [comment]
I was able to update dependencies in the repro repo in such a way that I think it's now reproducing the whole problem, not just that one part of it!

I'm now getting the following output from the `reproduce-issue.sh` script:
```
Diffing the original force-build's .next directory with the cache-hit-build's .next directory
Only in output/force-build/standalone/node_modules/.pnpm/next@14.1.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: postcss
Only in output/force-build/standalone/node_modules/.pnpm/next@14.1.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react
Only in output/force-build/standalone/node_modules/.pnpm/next@14.1.0_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react-dom
Only in output/force-build/standalone/node_modules/.pnpm/react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules: react
```

Sorry I didn't manage to capture that part of it before!

**Comment by chris-olszewski** [comment]
No worries, thanks for updating the repro.

I believe https://github.com/vercel/turbo/pull/7633 should fix the remaining diff issues.

**Comment by trappar** [comment]
Thanks! Let me know when there's a new canary version I can test against.

**Comment by chris-olszewski** [comment]
`1.12.5-canary.2` is out and has the additional fixes for symlinks! Keeping open in case you find some additional issues with your primary project.

**Comment by trappar** [comment]
**That seems to have done it! As of this version I'm once again able to run my server based purely on a cache-restored build without issue! 🎉** 

For full transparency, I am still seeing one line in the diff output:
```
diff: output/force-build/standalone/node_modules/.pnpm/node_modules/caniuse-lite: No such file or directory
```

But I'm fairly confident that issue has nothing to do with Turbo. I tried downgrading to `1.10.16` and I still see that on that version as well. I went looking for that file and I think the problem is that it's a broken symlink:

```bash
% pwd
/Users/trappar/[redacted]/.next/standalone/node_modules/.pnpm/node_modules
% ls -al
total 0
drwxr-xr-x   10 trappar  staff   320 Mar  5 17:14 .
drwxr-xr-x  204 trappar  staff  6528 Mar  5 17:14 ..
drwxr-xr-x    3 trappar  staff    96 Mar  5 17:14 @opentelemetry
lrwxr-xr-x    1 trappar  staff    54 Mar  5 17:14 caniuse-lite -> ../caniuse-lite@1.0.30001528/node_modules/caniuse-lite
lrwxr-xr-x    1 trappar  staff   114 Mar  5 17:14 next -> ../next@14.0.3_react-dom@18.3.0-canary-627b7abd6-20230911_react@18.3.0-canary-627b7abd6-20230911/node_modules/next
lrwxr-xr-x    1 trappar  staff    60 Mar  5 17:14 react -> ../react@18.3.0-canary-627b7abd6-20230911/node_modules/react
lrwxr-xr-x    1 trappar  staff    34 Mar  5 17:14 sharp -> ../sharp@0.31.3/node_modules/sharp
lrwxr-xr-x    1 trappar  staff    51 Mar  5 17:14 supports-color -> ../supports-color@7.2.0/node_modules/supports-color
lrwxr-xr-x    1 trappar  staff    42 Mar  5 17:14 uglify-js -> ../uglify-js@3.17.4/node_modules/uglify-js
lrwxr-xr-x    1 trappar  staff    71 Mar  5 17:14 webpack -> ../webpack@5.89.0_@swc+core@1.3.83_esbuild@0.17.19/node_modules/webpack
% ls -al .. | grep caniuse
drwxr-xr-x    3 trappar  staff    96 Mar  5 17:14 caniuse-lite@1.0.30001585
```

Notice that the link points at `caniuse-lite@1.0.30001528` but the version I have locally is `caniuse-lite@1.0.30001585`. (different numbers)

In the cache restored version the symlink still exists, so I think Turbo is working perfectly and diff is just complaining since it isn't able to find the file. Maybe this is a PNPM or Next.js bug? Either way it's not causing any issues so I'd say this is fixed!

**Comment by chris-olszewski** [comment]
> For full transparency, I am still seeing one line in the diff output

Ah, we intentionally don't restore broken symlinks, but I think that's acceptable? If we run into a tool that depends on broken symlinks existing we can reconsider that decision.

Again, thanks for the great reproduction/write up/testing of the fixes!
